console.log("Four or more ways to get the first paragraph with DOM Selectors");
console.log("document.getElementById(\"first\")");
console.log("document.getElementsByClassName(\"special\")[0]");
console.log("document.getElementsByTagName(\"p\")[0]");
console.log("document.querySelector(\"#first\")");
console.log("document.querySelector(\".special\")");
console.log("document.querySelector(\"p\")");
console.log("document.querySelectorAll(\"#first\")[0]");
console.log("document.querySelectorAll(\".special\")[0]");
console.log("document.querySelectorAll(\"p\")[0]");